### ISSUE TITLE
USER STORY: Admin can remove old polls

### ISSUE THREAD

**Issue by CozyPlantlady** [CozyPlantlady/my-first-agile-project#6]
As a **admin** I can **remove old polls** so that **there is less clutter in site**

## Acceptance Criteria
* Acceptance criteria 1: Admin can log in to the site
* Acceptance criteria 2: Admin can see all active and in-active polls
* Acceptance criteria 3: Admin can remove old polls
* Acceptance criteria 4: Admin can change order of polls

## Tasks
- [ ] Admin login
- [ ] Visible list of polls
- [ ] Drag and drop- option to change the order of polls
- [ ] Option to remove poll permanently
- [ ] Option to see when the poll has been active
