### ISSUE TITLE
USER STORY: User login to see runner status

### ISSUE THREAD

**Issue by CozyPlantlady** [CozyPlantlady/my-first-agile-project#7]
As a **user** I can **log in** so that **I can see my stats**

## Acceptance Criteria
* Acceptance criteria 1: User can log in with username and password
* Acceptance criteria 2: User can go to their personal page
* Acceptance criteria 3: User can see their stats they have submitted

## Tasks
- [ ] User login using Username and Password
- [ ] Personal pages for users
- [ ] Personal page has option to submit their running data
- [ ] A graph that shows their personal data that they have submitted
