### ISSUE TITLE
USER STORY: Admin rights to blocked/removed users

### ISSUE THREAD

**Issue by CozyPlantlady** [CozyPlantlady/my-first-agile-project#8]
As a **admin** I can **remove and block user** so that **badly behaving users can't login and comment**

## Acceptance Criteria
* Acceptance criteria 1: Only verified users can comment on posts
* Acceptance criteria 2: User can be blocked
* Acceptance criteria 3: User can be permanently removed
* Acceptance criteria 4: Once User is blocked/ removed they can't use the same logging in information to create a new account
* Acceptance criteria 5: Admin can see list of blocked users

## Tasks
- [ ] Create list of blocked user accounts
- [ ] Create list of verified user accounts
- [ ] Section for Admin to see said lists
- [ ] Let admin have rights to make changes to said lists

**Comment by CozyPlantlady** [comment]
This is completed
